### PR TITLE
Tagupdates

### PR DESCRIPTION
**Pull request by gknisely**
Eastbound and down:  Added truck logic.  Tested with planet.  
:truck:

### CODE REVIEW

**Comment by dgearhart** [comment]
... loaded up and truckin'
We gonna do what they say can't be done :+1:  :truck:

**Comment by kevinkreiser** [comment]
is this a song or something? i have a decent amount of trucking-related experience but none of these quotes are making sense to me!

**Comment by dgearhart** [comment]
yes from Smokey and the Bandit
https://www.youtube.com/watch?v=-ls-QEleksI

**Comment by gknisely** [comment]
@kevinkreiser lol

**Pull request merged**
