### PR TITLE
added matrix locations to costing options for limit checks

### PR DESCRIPTION
**Pull request by kdiluca**

### CODE REVIEW

**Comment by kevinkreiser** [comment]
why is this needed?

**Comment by kdiluca** [comment]
When we combined the limit checking for max locations and max distance, we loop thru the costing_options to get the key.  Right now, we can a seg fault because there are none for matrix.

**Comment by kevinkreiser** [comment]
we should check the matrix ones in a separate loop. we know the matrix names apriori, its why we have them in: https://github.com/valhalla/loki/blob/master/src/loki/service.cc#L31.

adding these to costing options doesnt make sense because they arent costing types

**Comment by kevinkreiser** [comment]
honestly itd be enough to just do something like:

    for(cons auto& matrix_type: std::list<std::string>{"one_to_many","many_to_one","many_to_many"}) {
      max_locations.emplace(matrix_type, config.get<size_t>("service_limits." + kv.first + ".max_locations"));
      max_distance.emplace(matrix_type, config.get<float>("service_limits." + kv.first + ".max_distance"));
    }

**Comment by dnesbitt61** [comment]
agree here

**Comment by dnesbitt61** [comment]
for(const auto& matrix_type: std::list<std::string>{"one_to_many","many_to_one","many_to_many"}) {
        max_locations.emplace(matrix_type, config.get<size_t>("service_limits." + matrix_type + ".max_locations"));
        max_distance.emplace(matrix_type, config.get<float>("service_limits." + matrix_type + ".max_distance"));
      }

**Comment by kdiluca** [comment]
yep, fixing now.  There still seems to be an issue with the distance.  Will submit 2nd PR with example. thanks!

**Pull request closed without merging**
