### PR TITLE
only throw out area ways when they are marked area=yes

### PR DESCRIPTION
**Pull request by kevinkreiser**

### CODE REVIEW

**Comment by kevinkreiser** [comment]
this fixes https://github.com/valhalla/thor/issues/317

or i hypothesize it will ;)

**Comment by gknisely** [comment]
Did you test via an extract?  Also, not sure now if we should toss them at all now after reading this: http://wiki.openstreetmap.org/wiki/Area

**Comment by kevinkreiser** [comment]
no i didnt test it, thats for the data director haha

`area=yes` on a way is basically a way of saying something is a polygon and its quite a widespread tagging convention IMHO. the only additional thing we could do is check that the linestring is actually a ring, `linestring[0] == linestring[linestring.size - 1]` but even then i guess i could see roundabouts that are a ring and also have area=yes. perhaps we need a combination of these things like:

    --only toss areas if they don't seem drivable
    if area=yes and ( !ring OR !unclassified ) then
      toss
    end

**Comment by kevinkreiser** [comment]
@gknisely it does fix the issue and i think its the least invasive way to move forward at the present time.

the suggestion above might be the best course of action in the future though, we can save that for the next iteration?

**Comment by gknisely** [comment]
:+1:

**Pull request merged**
